protected/modules/admincp/controllers/NewsController.php
<?php

class NewsController extends Controller
{
    //public $layout='column1';	

    /**
    * Declares class-based actions.
    */
    public function actions(){

    }

    /**
    * This is the action to handle external exceptions.
    */
    public function actionError(){
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
    * Displays the login page
    */
    public function actionIndex(){		        
        $data_news = AdminNews::getAllRows();        
        $this->render('index',array('data_news'=>$data_news));
    }

    public function actionAdd(){             
        $data_category = AdminCategory::getAllRows();
        $this->render('add',array('data_category'=>$data_category));
    }

    public function actionDetail(){        
        $news_id = isset($_GET["id"])?mysql_escape_string($_GET["id"]):"1";
        $data_new = AdminNews::getRowById($news_id);        
        $this->render('detail',array('data_new'=>$data_new));
    }

    public function actionAjaxChangeStatus(){          
        $url = new Url();                          
        $category_id = isset($_POST["category_id"])?mysql_escape_string($_POST["category_id"]):"";
        $data_update['is_hot'] = isset($_POST["is_hot_status"])?mysql_escape_string($_POST["is_hot_status"]):"";        
        echo AdminCategory::update($category_id,$data_update);
    }

    public function actionAjaxAddNew(){                  
        $url = new Url();                          
        $data_insert['news_title'] = isset($_POST["news_title"])?mysql_escape_string($_POST["news_title"]):"";                
        $data_insert['news_content'] = isset($_POST["news_content"])?$_POST["news_content"]:"";
        $data_insert['create_date'] = time();

        echo AdminNews::insert($data_insert);
    }

    public function actionAjaxEditNew(){                  
        $url = new Url();     
        $news_id = isset($_POST["news_id"])?mysql_escape_string($_POST["news_id"]):"";
        $data_insert['news_title'] = isset($_POST["news_title"])?mysql_escape_string($_POST["news_title"]):"";                
        $data_insert['news_content'] = isset($_POST["news_content"])?$_POST["news_content"]:"";        
        echo AdminNews::update($news_id,$data_insert);
    }

    public function actionAjaxDeleteNew(){                  
        $url = new Url();                          
        $author_id = isset($_POST["author_id"])?mysql_escape_string($_POST["author_id"]):"";                                
        echo AdminAuthor::delete("author_id = " . $author_id);
    }

}

protected/modules/admincp/views/news/add.php
<?php 
    $url = new Url();          
?> 
<div class="onecolumn" >
    <div class="header"><span><span class="ico gray window"></span>  Thêm mới tin tức  </span></div>
    <div class="clear"></div>
    <div class="content" >

        <form id="validation_demo" action="#">             
            <div class="section ">
                <label> Tiêu đề<small></small></label>   
                <div> 
                    <input type="text" class="validate[required] large" name="news_title" id="news_title" value="">
                </div>                                
            </div>                   
            <div class="section ">
                <label> Nội dung<small></small></label>   
                <div>                                     
                    <div>&nbsp;</div>      
                </div>                        
                <div style="margin-left : 0px ;"> <textarea name="news_content" id="news_content"  class="news_content" cols="" rows=""></textarea></div>
            </div>                                    
            <div class="section last">
                <div>                                    
                    <a class="uibutton submit_btn" onclick="add_new()" >Thêm tin tức</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script type="">    

    $(document).ready(function() {        
                           
        $(document).ready(function() {
            $("#news_content").cleditor({
                width:        "100%", // width not including margins, borders or padding
                height:       600, // height not including margins, borders or padding
                controls:     // controls to add to the toolbar
                "bold italic underline strikethrough subscript superscript | font size " +
                "style | color highlight removeformat | bullets numbering | outdent " +
                "indent | alignleft center alignright justify | undo redo | " +
                "rule image link unlink | cut copy paste pastetext | print source",
                colors:       // colors in the color popup
                "FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
                "CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
                "BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
                "999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
                "666 900 C60 C93 990 090 399 33F 60C 939 " +
                "333 600 930 963 660 060 366 009 339 636 " +
                "000 300 630 633 330 030 033 006 309 303",    
                fonts:        // font names in the font popup
                "Times New Roman,Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
                "Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
                sizes:        // sizes in the font size popup
                "1,2,3,4,5,6,7",
                styles:       // styles in the style popup
                [["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
                ["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
                ["Header 6","<h6>"]],
                useCSS:       false, // use CSS to style HTML when possible (not supported in ie)
                docType:      // Document type contained within the editor
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
                docCSSFile:   // CSS file used to style the document contained within the editor
                "", 
                bodyStyle:    // style to assign to document body contained within the editor
                "margin:4px; font:20px; cursor:text;text-align:justify"
            });
        });

    }); 

    function add_new(){                
        if($("form#validation_demo").validationEngine('validate')){
            var news_title = $('#news_title').val();
            var news_content = $('#news_content').val();            

            /*if(author_image == ''){
                alert('Bạn chưa chọn danh mục!');
                return false;
            }*/

            loading('Xử lý',1);                                                
            var strUrl = '<?php echo $url->createUrl("news/ajaxAddNew"); ?>';         
            $.ajax({
                type: "POST",
                url: strUrl,            
                data: {news_title:news_title,news_content:news_content}, 
                beforeSend: function() {

                },
                complete: function() {                    
                    setTimeout( "unloading()", 1000 );                           
                },
                success: function(msg){                    
                    if(msg == -1){                       
                        setTimeout('showError("Tên truyện đã tồn tại!")',100);                                                    
                    }else{                        
                        window.location.href='<?php echo $url->createUrl("news/index"); ?>';
                    }
                }
            })
        }
    }

</script>

protected/modules/admincp/views/news/detail.php
<?php 
    $url = new Url();          
?> 

<div class="onecolumn" >
    <div class="header"><span><span class="ico gray window"></span>  Chi tiết tin tức  </span></div>
    <div class="clear"></div>
    <div class="content" >

        <form id="validation_demo" action="#">       
            <input type="hidden" id="news_id" name="news_id" value="<?php echo $data_new['id']; ?>">      
            <div class="section ">
                <label> Tiêu đề<small></small></label>   
                <div> 
                    <input type="text" class="validate[required] large" name="news_title" id="news_title" value="<?php echo $data_new['news_title']; ?>">
                </div>                                
            </div>                   
            <div class="section ">
                <label> Nội dung<small></small></label>   
                <div>                                     
                    <div>&nbsp;</div>      
                </div>                        
                <div style="margin-left : 0px ;"> <textarea name="news_content" id="news_content"  class="news_content" cols="" rows=""><?php echo $data_new['news_content']; ?></textarea></div>
            </div>                                    
            <div class="section last">
                <div>                                    
                    <a class="uibutton submit_btn" onclick="update_news()" >Sửa tin tức</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script type="">

    $(document).ready(function() {        

        $(document).ready(function() {
            $("#news_content").cleditor({
                width:        "100%", // width not including margins, borders or padding
                height:       600, // height not including margins, borders or padding
                controls:     // controls to add to the toolbar
                "bold italic underline strikethrough subscript superscript | font size " +
                "style | color highlight removeformat | bullets numbering | outdent " +
                "indent | alignleft center alignright justify | undo redo | " +
                "rule image link unlink | cut copy paste pastetext | print source",
                colors:       // colors in the color popup
                "FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
                "CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
                "BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
                "999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
                "666 900 C60 C93 990 090 399 33F 60C 939 " +
                "333 600 930 963 660 060 366 009 339 636 " +
                "000 300 630 633 330 030 033 006 309 303",    
                fonts:        // font names in the font popup
                "Times New Roman,Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
                "Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
                sizes:        // sizes in the font size popup
                "1,2,3,4,5,6,7",
                styles:       // styles in the style popup
                [["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
                ["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
                ["Header 6","<h6>"]],
                useCSS:       false, // use CSS to style HTML when possible (not supported in ie)
                docType:      // Document type contained within the editor
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
                docCSSFile:   // CSS file used to style the document contained within the editor
                "", 
                bodyStyle:    // style to assign to document body contained within the editor
                "margin:4px; font:20px; cursor:text;text-align:justify"
            });
        });

    }); 

    function update_news(){                
        if($("form#validation_demo").validationEngine('validate')){
            var news_id = $('#news_id').val();            
            var news_title = $('#news_title').val();                        
            var news_content = $('#news_content').val();            

            /*if(author_image == ''){
            alert('Bạn chưa chọn danh mục!');
            return false;
            }*/

            loading('Xử lý',1);                                                
            var strUrl = '<?php echo $url->createUrl("news/ajaxEditNew"); ?>';         
            $.ajax({
                type: "POST",
                url: strUrl,            
                data: {news_id:news_id,news_title:news_title,news_content:news_content}, 
                beforeSend: function() {

                },
                complete: function() {                    
                    setTimeout( "unloading()", 1000 );                           
                },
                success: function(msg){                    
                    if(msg == -1){                       
                        setTimeout('showError("Tên truyện đã tồn tại!")',100);                                                    
                    }else{                        
                        window.location.href='<?php echo $url->createUrl("news/index"); ?>';
                    }
                }
            })
        }
    }

</script>

protected/modules/admincp/views/news/index.php
<?php 
    $url = new Url(); 
?>    
<div class="onecolumn" >
    <div class="header"><span ><span class="ico  gray bookmark"></span>Quản lý tin tức</span> </div>
    <div class="clear"></div>
    <div class="content" >    
        <div id="uploadTab">
            <ul class="tabs" >
                <li><a href="#tab2" id="3">  Danh sách tin tức  <img src="<?php echo Yii::app()->params['urlRsAdmin'];?>/images/icon/new.gif" width="20" height="9" /></a></li>                
            </ul>
            <div class="tab_container">

                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><span class="tip"><a class="uibutton icon add" title="Click để thêm tin tức" href="<?php echo $url->createUrl("news/add"); ?>">Thêm tin tức</a></span></li>
                        </ul>
                        <form class="tableName toolbar">

                            <h3>Danh sách tin tức</h3>                            
                            <table class="display data_table2" id="data_table">
                                <thead>
                                    <tr>
                                        <!--<th width="35" ><input type="checkbox" id="checkAll1"  class="checkAll"/></th>-->
                                        <th width="20" >ID</th>
                                        <th width="250" align="left">Tiêu đề</th>                                                                                
                                        <th width="" >Nội dung</th>
                                        <th width="120" >Trạng thái</th>
                                        <th width="120" >Quản lý</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    <?php for($i=0;$i<count($data_news);$i++){ ?>

                                        <tr>
                                            <td><?php echo $data_news[$i]['id'];  ?></td>
                                            <td align="left"><?php echo $data_news[$i]['news_title'];  ?></td>                                                                                    
                                            <td><?php $content = $data_news[$i]['news_content'];$content = StringUtils::cutstring($content,200,true);$content = nl2br($content);  echo $content;  ?></td>
                                            <td id="is_hot_row_<?php echo $data_news[$i]['id']; ?>">
                                                <a href="javascript:"><span class="ico shadow checkmark2 <?php if($data_news[$i]['news_status'] == 1){echo "color";}else{echo "gray";} ?>"></span></a>
                                            </td>                                            
                                            <td >                                                
                                                <span class="tip" >
                                                    <a title="Sửa" href="<?php echo $url->createUrl("news/detail",array("id"=>$data_news[$i]['id'])); ?>" >
                                                        <img src="<?php echo Yii::app()->params['urlRsAdmin'];?>/images/icon/icon_edit.png" >
                                                    </a>                                                                
                                                </span>&nbsp;
                                                <span class="tip" >
                                                    <a value="<?php echo $data_author[$i]['author_id']; ?>" class="Delete" name="<?php echo $data_news[$i]['news_title'];  ?>" title="Xóa"  >
                                                        <img src="<?php echo Yii::app()->params['urlRsAdmin'];?>/images/icon/icon_delete.png" >
                                                    </a>
                                                </span>                                                                                    
                                            </td> 
                                        </tr>

                                        <?php } ?>                            

                                </tbody>
                            </table>
                        </form>
                    </div>    
                </div>                

            </div> 
        </div>
        <div class="clear"/></div>                   
</div>
</div>

<script>    

    $(document).ready(function() {
        //$("#post_content").cleditor()[0].focus();
        
        $(document).ready(function() {
            $("#post_content").cleditor({
                width:        500, // width not including margins, borders or padding
                height:       250, // height not including margins, borders or padding
                controls:     // controls to add to the toolbar
                "bold italic underline strikethrough subscript superscript | font size " +
                "style | color highlight removeformat | bullets numbering | outdent " +
                "indent | alignleft center alignright justify | undo redo | " +
                "rule image link unlink | cut copy paste pastetext | print source",
                colors:       // colors in the color popup
                "FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
                "CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
                "BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
                "999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
                "666 900 C60 C93 990 090 399 33F 60C 939 " +
                "333 600 930 963 660 060 366 009 339 636 " +
                "000 300 630 633 330 030 033 006 309 303",    
                fonts:        // font names in the font popup
                "Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
                "Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
                sizes:        // sizes in the font size popup
                "1,2,3,4,5,6,7",
                styles:       // styles in the style popup
                [["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
                ["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
                ["Header 6","<h6>"]],
                useCSS:       false, // use CSS to style HTML when possible (not supported in ie)
                docType:      // Document type contained within the editor
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
                docCSSFile:   // CSS file used to style the document contained within the editor
                "", 
                bodyStyle:    // style to assign to document body contained within the editor
                "margin:4px; font:10pt Arial,Verdana; cursor:text"
            });
        });
        
    });    

    $(".Delete").live('click',function() {         
        var author_id = $(this).attr("value");                
        var row=$(this).parents('tr');
        var dataSet=$(this).parents('form');
        var id = $(this).attr("id");
        var name = $(this).attr("name");        
        var data ='id='+id;        
        Delete(data,name,row,0,dataSet,author_id);
    });

    function Delete(data,name,row,type,dataSet,author_id){
        var loadpage = dataSet.hdata(0);
        var url = dataSet.hdata(1);
        var table = dataSet.hdata(2);
        var data = data+"&tabel="+table;
        $.confirm({
            'title': 'Xóa dữ liệu','message': " <strong>Bạn có muốn xóa </strong><br /><font color=red>' "+ name +" ' </font> ",'buttons': {'Chấp nhận': {'class': 'special',
                    'action': function(){
                        loading('Checking');
                        delete_author(author_id);
                        $('#preloader').html('Đang xóa');
                        if(type==0){ row.slideUp(function(){   showSuccess('Thành công',5000); unloading(); }); return false;}
                        if(type==1){ row.slideUp(function(){   showSuccess('Thành công',5000); unloading(); }); return false;}
                        setTimeout("unloading();",900);          
                }},'Hủy bỏ'    : {'class'    : ''}}});}

    function delete_author(author_id){

        var strUrl = '<?php echo $url->createUrl("news/ajaxDeleteAuthor"); ?>';         
        $.ajax({
            type: "POST",
            url: strUrl,            
            data: {author_id:author_id}, 
            beforeSend: function() {

            },
            complete: function() {

            },
            success: function(msg){                

            }
        })
    }    

    function change_is_hot(post_id,is_hot){
        var is_hot_status = 1;
        var text_color = "color";
        if(is_hot == 1){
            is_hot_status = 0;
            text_color = "gray";
        }
        loading('Xử lý',1);                                                
        var strUrl = '<?php echo $url->createUrl("news/ajaxChangeStatus"); ?>';         
        $.ajax({
            type: "POST",
            url: strUrl,            
            data: {post_id:post_id,is_hot_status:is_hot_status}, 
            beforeSend: function() {

            },
            complete: function() {
                setTimeout( "unloading()", 1000 );                    
            },
            success: function(msg){                
                if(msg == 1){                       
                    $('#is_hot_row_'+post_id).html('<a href="javascript:" onclick="change_is_hot('+post_id+','+is_hot_status+')"><span class="ico shadow checkmark2 '+text_color+'"></span></a>');
                }
            }
        })
    }

</script>